version: "3.7"
# This file is created in order to conduct experiments with a local Cassandra Cluster that mimics the prime
# environment
# We need to create aliases for existing interface lo0 in order to be able to bind to different IP Addresses
# locally
# https://stackoverflow.com/questions/69956055/is-it-possible-to-bind-on-another-ip-than-127-0-0-1-on-macos
#
# sudo ifconfig lo0 alias 172.25.0.10 netmask 0xff000000
# sudo ifconfig lo0 alias 172.25.0.11 netmask 0xff000000
# sudo ifconfig lo0 alias 172.25.0.12 netmask 0xff000000
#
# Make sure to execute following command to setup the system:
# Helenus.Schema.create_schema_for_system([nodes: ["172.25.0.10"]], :prime, :vpp)
services:
  cassandra-1:
    image: cassandra:latest
    container_name: "cassandra-1"
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3"
      - "CASSANDRA_CLUSTER_NAME=local_cluster"
      - "CASSANDRA_DC=berlin"
      - "CASSANDRA_RACK=b1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    networks:
      cassandra_network:
        ipv4_address: 172.25.0.10
    volumes:
      - cassandra-1-data:/var/lib/cassandra

  cassandra-2:
    image: cassandra:latest
    container_name: "cassandra-2"
    ports:
      - "9043:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3"
      - "CASSANDRA_CLUSTER_NAME=local_cluster"
      - "CASSANDRA_DC=berlin"
      - "CASSANDRA_RACK=b1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    depends_on:
      - "cassandra-1"
    networks:
      cassandra_network:
        ipv4_address: 172.25.0.11
    volumes:
      - cassandra-2-data:/var/lib/cassandra

  cassandra-3:
    image: cassandra:latest
    ports:
      - "9044:9042"
    container_name: "cassandra-3"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
      - "CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3"
      - "CASSANDRA_CLUSTER_NAME=local_cluster"
      - "CASSANDRA_DC=berlin"
      - "CASSANDRA_RACK=b1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
    depends_on:
      - "cassandra-2"
    networks:
      cassandra_network:
        ipv4_address: 172.25.0.12
    volumes:
      - cassandra-3-data:/var/lib/cassandra

  # cassandra-4:
  #   image: cassandra:latest
  #   container_name: "cassandra-4"
  #   environment:
  #     - "MAX_HEAP_SIZE=256M"
  #     - "HEAP_NEWSIZE=128M"
  #     - "CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3,cassandra-4,cassandra-5,cassandra-6"
  #     - "CASSANDRA_CLUSTER_NAME=local_cluster"
  #     - "CASSANDRA_DC=munich"
  #     - "CASSANDRA_RACK=m1"
  #     - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
  #   networks:
  #     cassandra_network:
  #       ipv4_address: 172.25.0.13
  #   volumes:
  #     - cassandra-4-data:/var/lib/cassandra

  # cassandra-5:
  #   image: cassandra:latest
  #   container_name: "cassandra-5"
  #   environment:
  #     - "MAX_HEAP_SIZE=256M"
  #     - "HEAP_NEWSIZE=128M"
  #     - "CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3,cassandra-4,cassandra-5,cassandra-6"
  #     - "CASSANDRA_CLUSTER_NAME=local_cluster"
  #     - "CASSANDRA_DC=munich"
  #     - "CASSANDRA_RACK=m1"
  #     - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
  #   depends_on:
  #     - "cassandra-1"
  #   networks:
  #     cassandra_network:
  #       ipv4_address: 172.25.0.14
  #   volumes:
  #     - cassandra-5-data:/var/lib/cassandra

  # cassandra-6:
  #   image: cassandra:latest
  #   container_name: "cassandra-6"
  #   environment:
  #     - "MAX_HEAP_SIZE=256M"
  #     - "HEAP_NEWSIZE=128M"
  #     - "CASSANDRA_SEEDS=cassandra-1,cassandra-2,cassandra-3,cassandra-4,cassandra-5,cassandra-6"
  #     - "CASSANDRA_CLUSTER_NAME=local_cluster"
  #     - "CASSANDRA_DC=munich"
  #     - "CASSANDRA_RACK=m1"
  #     - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
  #   depends_on:
  #     - "cassandra-2"
  #   networks:
  #     cassandra_network:
  #       ipv4_address: 172.25.0.15
  #   volumes:
  #     - cassandra-6-data:/var/lib/cassandra

  elixir_app:
    build:
      context: .
    container_name: elixir_app
    networks:
      cassandra_network:
        aliases:
          - elixir_app
    ports:
      - "4000:4000"
    volumes:
      - .:/app

networks:
  cassandra_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

volumes:
  cassandra-1-data:
  cassandra-2-data:
  cassandra-3-data:
  # cassandra-4-data:
  # cassandra-5-data:
  # cassandra-6-data:
