defmodule Xandra.Cluster.TokenTest do
  use ExUnit.Case, async: true

  alias Xandra.Cluster.Token
  alias Xandra.Cluster.Token.Murmur3
  alias Xandra.Prepared

  @min_token -9_223_372_036_854_775_808
  @max_token 9_223_372_036_854_775_807

  describe "Murmur3.hash/1" do
    # Test vectors verified against the ScyllaDB Python driver's murmur3
    # implementation (https://github.com/scylladb/python-driver, cassandra/murmur3.py)
    # and gocql's test suite (internal/murmur/murmur_test.go).
    @murmur3_vectors [
      {<<>>, 0},
      {<<0, 0, 0, 0>>, -3_485_513_579_396_041_028},
      {<<0, 0, 0, 1>>, -4_069_959_284_402_364_209},
      {<<0xFF, 0xFF, 0xFF, 0xFF>>, 7_297_452_126_230_313_552},
      {<<0, 0, 0, 42>>, -7_160_136_740_246_525_330},
      {<<0, 0, 0, 0, 0, 0, 0, 1>>, 6_292_367_497_774_912_474},
      {"hello", -3_758_069_500_696_749_310},
      {"hello, world", 3_760_413_751_763_713_166},
      {"0", 3_083_240_331_115_144_064},
      {"0123456789", 4_581_940_570_640_870_180},
      {<<0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF, 0xFF>>, 7_071_048_584_287_372_947},
      # Bytes >= 0x80 exercise Cassandra's signed-byte reads of the tail.
      {<<0x80>>, -5_284_281_814_142_962_636},
      # Composite routing key from gocql's TestMurmur3H1_CassandraSign.
      {Base.decode16!("00104327529FB645DD00B883EC39AE448BB800000400066A6B00", case: :upper),
       -9_223_371_632_693_506_265}
    ]

    test "matches the reference Cassandra Murmur3 implementation" do
      for {input, expected_token} <- @murmur3_vectors do
        assert Murmur3.hash(input) == expected_token,
               "expected hash of #{inspect(input)} to be #{expected_token}"
      end
    end
  end

  describe "shard/3" do
    # Test vectors generated by executing the ScyllaDB Python driver's
    # _ShardingInfo.shard_id_from_token (cassandra/shard_info.py).
    @shard_vectors [
      {2, 12, @min_token, 0},
      {2, 12, -1, 1},
      {2, 12, 0, 0},
      {2, 12, 1, 0},
      {2, 12, @max_token, 1},
      {4, 12, -4_069_959_284_402_364_209, 1},
      {4, 12, -1, 3},
      {4, 12, 0, 0},
      {4, 12, 1_234_567_890_123_456_789, 0},
      {8, 12, -4_069_959_284_402_364_209, 2},
      {8, 12, -1, 7},
      {8, 12, 1_234_567_890_123_456_789, 1},
      {12, 12, -4_069_959_284_402_364_209, 3},
      {12, 12, -1, 11},
      {7, 12, -1, 6},
      {7, 12, -4_069_959_284_402_364_209, 2},
      {4, 0, 0, 2},
      {4, 0, 1, 2},
      {4, 0, -1, 1},
      {4, 0, @min_token, 0},
      {4, 0, @max_token, 3}
    ]

    test "matches ScyllaDB's biased-token-round-robin algorithm" do
      for {nr_shards, ignore_msb, token, expected_shard} <- @shard_vectors do
        assert Token.shard(token, nr_shards, ignore_msb) == expected_shard,
               "expected shard(#{token}, #{nr_shards}, #{ignore_msb}) to be #{expected_shard}"
      end
    end
  end

  describe "for_routing_key/1" do
    test "normalizes the minimum token to the maximum token" do
      # The empty routing key hashes to 0, so craft the normalization check
      # directly through the hash: we can't easily find a key that hashes to
      # the min token, so we just check that no computed token is ever the
      # min token by construction of for_routing_key/1.
      assert Token.for_routing_key(<<>>) == 0
      assert Token.for_routing_key(<<0, 0, 0, 42>>) == -7_160_136_740_246_525_330
    end
  end

  describe "compute/2" do
    defp prepared(fields) do
      struct!(
        %Prepared{protocol_module: Xandra.Protocol.V4},
        fields
      )
    end

    test "computes the token from a single-component partition key" do
      prepared =
        prepared(
          bound_columns: [{"ks", "table", "code", :int}],
          pk_indices: [0]
        )

      # The routing key is the raw serialized int, so this matches the
      # murmur3 vector for <<0, 0, 0, 42>>.
      assert Token.compute(prepared, [42]) == {:ok, -7_160_136_740_246_525_330}
    end

    test "computes the token for composite partition keys" do
      # From gocql's TestMurmur3H1_CassandraSign: a (timeuuid, int) composite
      # key. Each component is <<size::16, component::binary, 0>>.
      timeuuid = Base.decode16!("4327529FB645DD00B883EC39AE448BB8", case: :upper)

      prepared =
        prepared(
          bound_columns: [
            {"ks", "table", "id", :timeuuid},
            {"ks", "table", "code", :int},
            {"ks", "table", "other", :text}
          ],
          pk_indices: [0, 1]
        )

      assert Token.compute(prepared, [timeuuid, 0x00066A6B, "not part of the pk"]) ==
               {:ok, -9_223_371_632_693_506_265}
    end

    test "supports named params" do
      prepared =
        prepared(
          bound_columns: [{"ks", "table", "code", :int}],
          pk_indices: [0]
        )

      assert Token.compute(prepared, %{"code" => 42}) == {:ok, -7_160_136_740_246_525_330}
    end

    test "returns :error when there are no partition key indices" do
      assert Token.compute(prepared(bound_columns: [], pk_indices: nil), []) == :error
      assert Token.compute(prepared(bound_columns: [], pk_indices: []), []) == :error
    end

    test "returns :error when partition key values are nil or :not_set" do
      prepared =
        prepared(
          bound_columns: [{"ks", "table", "code", :int}],
          pk_indices: [0]
        )

      assert Token.compute(prepared, [nil]) == :error
      assert Token.compute(prepared, [:not_set]) == :error
    end

    test "returns :error instead of raising on missing or invalid values" do
      prepared =
        prepared(
          bound_columns: [{"ks", "table", "code", :int}],
          pk_indices: [0]
        )

      assert Token.compute(prepared, []) == :error
      assert Token.compute(prepared, ["not an int"]) == :error
      assert Token.compute(prepared, %{"other" => 1}) == :error
    end
  end
end
