name: CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MIX_ENV: test

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Clone the repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install OTP and Elixir
        id: setup_beam
        uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: "27.2"
          elixir-version: "1.18"

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            deps
            _build
          key: |
            ${{ runner.os }}-lint-otp${{ steps.setup_beam.outputs['otp-version'] }}-elixir${{ steps.setup_beam.outputs['elixir-version'] }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-lint-otp${{ steps.setup_beam.outputs['otp-version'] }}-elixir${{ steps.setup_beam.outputs['elixir-version'] }}-

      - name: Install and compile dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mix deps.get --check-locked

      - name: Check formatting
        run: mix format --check-formatted

      - name: Check no unused dependencies
        run: mix deps.unlock --check-unused
        if: ${{ steps.cache-deps.outputs.cache-hit != 'true' }}

      - name: Compile with --warnings-as-errors
        run: mix compile --warnings-as-errors --force

      - name: Cache Dialyzer's PLT
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: cache-plt
        with:
          path: plts
          key: |
            ${{ runner.os }}-plt-otp${{ steps.setup_beam.outputs['otp-version'] }}-elixir${{ steps.setup_beam.outputs['elixir-version'] }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-plt-otp${{ steps.setup_beam.outputs['otp-version'] }}-elixir${{ steps.setup_beam.outputs['elixir-version'] }}-

      # Create PLTs if no cache was found
      - name: Create PLTs
        if: steps.cache-plt.outputs.cache-hit != 'true'
        run: mix dialyzer --plt

      - name: Run Dialyzer
        run: mix dialyzer --format github

  test:
    name: >-
      Test (Elixir ${{ matrix.runtime.elixir }},
      OTP ${{ matrix.runtime.otp }} —
      C* ${{ matrix.server_versions.cassandra }},
      Scylla ${{ matrix.server_versions.scylla }})

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        runtime:
          # Oldest supported versions.
          - otp: "25.3"
            elixir: "1.15.4"
          # Latest supported versions.
          - otp: "27.2"
            elixir: "1.18"

        server_versions:
          - cassandra: "3"
            scylla: "4.6.3"
          - cassandra: "4.1"
            scylla: "5.2"

    env:
      CASSANDRA_VERSION: ${{ matrix.server_versions.cassandra }}
      SCYLLA_VERSION: ${{ matrix.server_versions.scylla }}
      LOG_LEVEL: debug

    steps:
      - name: Clone the repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Start Docker and wait for it to be up
        run: |
          docker compose up --detach --build
          ./test/docker/health-check-services.sh

      - name: Install OTP and Elixir
        uses: erlef/setup-beam@54075bcc5e249e4758d363f27d099f55d843f124 # v1.24.1
        with:
          otp-version: ${{ matrix.runtime.otp }}
          elixir-version: ${{ matrix.runtime.elixir }}

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            deps
            _build
          key: |
            ${{ runner.os }}-mix-otp${{ matrix.runtime.otp }}-elixir${{ matrix.runtime.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys:
            ${{ runner.os }}-mix-otp${{ matrix.runtime.otp }}-elixir${{ matrix.runtime.elixir }}-

      - name: Install and compile dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: mix deps.get --only test

      # TODO: eventually figure out why we can't run encryption tests on CI.
      - name: Run tests for Cassandra and Scylla (without coverage)
        run: mix test.all --exclude encryption --exclude toxiproxy

      - name: Dump Docker logs on failure
        uses: jwalton/gh-docker-logs@54a2a89cd6a2c929525f26ca67a7a4857a5dc1d9 # v1.0.1
        if: failure()
